package br.com.clientes.models;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import java.util.List;
import java.util.Map;

@Getter
@Setter
@Builder
public class RealmRepresentation {

    private String id;
    private String realm;
    private int notBefore;
    private String defaultSignatureAlgorithm;
    private boolean revokeRefreshToken;
    private int refreshTokenMaxReuse;
    private int accessTokenLifespan;
    private int accessTokenLifespanForImplicitFlow;
    private int ssoSessionIdleTimeout;
    private int ssoSessionMaxLifespan;
    private int ssoSessionIdleTimeoutRememberMe;
    private int ssoSessionMaxLifespanRememberMe;
    private int offlineSessionIdleTimeout;
    private boolean offlineSessionMaxLifespanEnabled;
    private int offlineSessionMaxLifespan;
    private int clientSessionIdleTimeout;
    private int clientSessionMaxLifespan;
    private int clientOfflineSessionIdleTimeout;
    private int clientOfflineSessionMaxLifespan;
    private int accessCodeLifespan;
    private int accessCodeLifespanUserAction;
    private int accessCodeLifespanLogin;
    private int actionTokenGeneratedByAdminLifespan;
    private int actionTokenGeneratedByUserLifespan;
    private int oauth2DeviceCodeLifespan;
    private int oauth2DevicePollingInterval;
    private boolean enabled;
    private String sslRequired;
    private boolean registrationAllowed;
    private boolean registrationEmailAsUsername;
    private boolean rememberMe;
    private boolean verifyEmail;
    private boolean loginWithEmailAllowed;
    private boolean duplicateEmailsAllowed;
    private boolean resetPasswordAllowed;
    private boolean editUsernameAllowed;
    private boolean bruteForceProtected;
    private boolean permanentLockout;
    private int maxTemporaryLockouts;
    private int maxFailureWaitSeconds;
    private int minimumQuickLoginWaitSeconds;
    private int waitIncrementSeconds;
    private int quickLoginCheckMilliSeconds;
    private int maxDeltaTimeSeconds;
    private int failureFactor;
    private RoleRepresentation defaultRole;
    private List<String> requiredCredentials;
    private String otpPolicyType;
    private String otpPolicyAlgorithm;
    private int otpPolicyInitialCounter;
    private int otpPolicyDigits;
    private int otpPolicyLookAheadWindow;
    private int otpPolicyPeriod;
    private boolean otpPolicyCodeReusable;
    private List<String> otpSupportedApplications;
    private String webAuthnPolicyRpEntityName;
    private List<String> webAuthnPolicySignatureAlgorithms;
    private String webAuthnPolicyRpId;
    private String webAuthnPolicyAttestationConveyancePreference;
    private String webAuthnPolicyAuthenticatorAttachment;
    private String webAuthnPolicyRequireResidentKey;
    private String webAuthnPolicyUserVerificationRequirement;
    private int webAuthnPolicyCreateTimeout;
    private boolean webAuthnPolicyAvoidSameAuthenticatorRegister;
    private List<String> webAuthnPolicyAcceptableAaguids;
    private List<String> webAuthnPolicyExtraOrigins;
    private String webAuthnPolicyPasswordlessRpEntityName;
    private List<String> webAuthnPolicyPasswordlessSignatureAlgorithms;
    private String webAuthnPolicyPasswordlessRpId;
    private String webAuthnPolicyPasswordlessAttestationConveyancePreference;
    private String webAuthnPolicyPasswordlessAuthenticatorAttachment;
    private String webAuthnPolicyPasswordlessRequireResidentKey;
    private String webAuthnPolicyPasswordlessUserVerificationRequirement;
    private int webAuthnPolicyPasswordlessCreateTimeout;
    private boolean webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister;
    private List<String> webAuthnPolicyPasswordlessAcceptableAaguids;
    private List<String> webAuthnPolicyPasswordlessExtraOrigins;
    private BrowserSecurityHeaders browserSecurityHeaders;
    private Map<String, Object> smtpServer;
    private boolean eventsEnabled;
    private List<String> eventsListeners;
    private List<String> enabledEventTypes;
    private boolean adminEventsEnabled;
    private boolean adminEventsDetailsEnabled;
    private List<Object> identityProviders;
    private List<Object> identityProviderMappers;
    private boolean internationalizationEnabled;
    private List<String> supportedLocales;
    private String browserFlow;
    private String registrationFlow;
    private String directGrantFlow;
    private String resetCredentialsFlow;
    private String clientAuthenticationFlow;
    private String dockerAuthenticationFlow;
    private String firstBrokerLoginFlow;
    private Map<String, String> attributes;
    private boolean userManagedAccessAllowed;
    private String loginTheme;
    private String defaultLocale;
}
